### ISSUE TITLE
echoとmysqlでサーバーサイドの基盤作成

### ISSUE THREAD

**Issue by mipo1357** [gisucoinc/ebisuiru-fc#3]

**Comment by KyoheiNakamura** [comment]
本来ならPR 出すべきですが develop 作ってそのまま push しちゃったのでとりあえずここにやったこと書いておきます。

[ebisuiru-fc-server](https://github.com/gisucoinc/ebisuiru-fc-server)

## やったこと
- Dockerfile, docker-compose.yml の作成
- devcontainer.json の作成
- docker-compose を使用しての Echo と Mysql の疎通確認
  - https://github.com/nishina555/echo-gorm-crud-api-example を真似してひとまず動くようにしてます
- docker 起動時に VSCode 推奨の Go 開発用ツール群とホットリロード用ツールのインストール

など。

## 動作確認方法
1. `.env.example` ファイルの中身をコピペして `.env` ファイルを作成
2. プロジェクト直下で `docker compose up` して API サーバーと DB を立ち上げる
4. `curl -X GET "http://localhost:8080/users"` を叩いてレスポンスが返ってくることを確認する

**Comment by KyoheiNakamura** [comment]
@mipo1357 
動作確認お願いします🙇‍♂️

**Comment by KyoheiNakamura** [comment]
test
